version: "3"

services:
    php:
        build:
            context: ./src/giaodien
            dockerfile: ./Dockerfile
        container_name: php_container
        ports:
            - "8080:80"
        networks:
            - app-network
        links:
            - mysql_container

    mysql_container:
        build:
            context: ./db
            dockerfile: ./Dockerfile
        container_name: mysql_container
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: caycanh
        networks:
            - app-network

networks:
    app-network:
        driver: bridge